# Generated by Django 3.2.8 on 2022-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_time',
            field=models.DateTimeField(max_length=10),
        ),
    ]
