# Generated by Django 3.2.8 on 2022-07-16 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline_Companie',
            new_name='Airline_Company',
        ),
        migrations.AlterField(
            model_name='user_role',
            name='role_name',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Airline Company', 'Airline Company'), ('Admin', 'Admin')], default='Customer', max_length=20, unique=True),
        ),
    ]
