# Generated by Django 3.2.8 on 2022-07-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220716_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Credit_Card',
            new_name='credit_Card',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone_No',
            new_name='phone_No',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='_id',
        ),
        migrations.AddField(
            model_name='user_role',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
