# Generated by Django 3.2.8 on 2022-07-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220717_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_Card',
            field=models.CharField(max_length=16),
        ),
    ]
